-- @autor Mateus Felipe _ mateus@doglee.com
-- This table was created to save the access and the main data for a client

DROP DATABASE IF EXISTS vitrini_webservice;
CREATE DATABASE vitrini_webservice;
USE vitrini_webservice;

CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `analise_numero_dependentes` VARCHAR(256),
  `analise_paga_aluguel` VARCHAR(256),
  `analise_regime_casamento` VARCHAR(256),
  `analise_ultima_cidade` VARCHAR(256),
  `banco_agencia` VARCHAR(256),
  `banco_cidade` VARCHAR(256),
  `banco_endereco` VARCHAR(256),
  `banco_nome` VARCHAR(256),
  `bens_banco` VARCHAR(256),
  `bens_imoveis` VARCHAR(256),
  `bens_veiculos` VARCHAR(256),
  `conjuge_atividade_remunerada` VARCHAR(256),
  `conjuge_cpf` VARCHAR(256),
  `conjuge_date` VARCHAR(256),
  `conjuge_email` VARCHAR(256),
  `conjuge_empresa_cargo` VARCHAR(256),
  `conjuge_empresa_data` VARCHAR(256),
  `conjuge_empresa_nome` VARCHAR(256),
  `conjuge_empresa_salario` VARCHAR(256),
  `conjuge_empresa_telefone` VARCHAR(256),
  `conjuge_nacionalidade` VARCHAR(256),
  `conjuge_name` VARCHAR(256),
  `conjuge_naturalidade` VARCHAR(256),
  `conjuge_profissao` VARCHAR(256),
  `conjuge_rg` VARCHAR(256),
  `endereco_bairro` VARCHAR(256),
  `endereco_cep` VARCHAR(256),
  `endereco_cidade` VARCHAR(256),
  `endereco_complemento` VARCHAR(256),
  `endereco_logradouro` VARCHAR(256),
  `endereco_numero` VARCHAR(256),
  `endereco_uf` VARCHAR(256),
  `imovel_cidade` VARCHAR(256),
  `imovel_endereco` VARCHAR(256),
  `imovel_quitado` VARCHAR(256),
  `imovel_registro` VARCHAR(256),
  `imovel_valor` VARCHAR(256),
  `participacao_socidedade` VARCHAR(256),
  `referencias` VARCHAR(256),
  `referencias_endereco` VARCHAR(256),
  `referencias_nome` VARCHAR(256),
  `referencias_parentesco` VARCHAR(256),
  `referencias_telefone` VARCHAR(256),
  `renda_fonte_renda` VARCHAR(256),
  `sociedade_capital_social` VARCHAR(256),
  `sociedade_cargo_funcao` VARCHAR(256),
  `sociedade_cnpj` VARCHAR(256),
  `sociedade_data` VARCHAR(256),
  `sociedade_empresa` VARCHAR(256),
  `sociedade_participacao` VARCHAR(256),
  `sociedade_registro` VARCHAR(256),
  `sociedade_ultima_data` VARCHAR(256),
  `submit_button` VARCHAR(256),
  `telefone_aluguel` VARCHAR(256),
  `tempo_aluguel` VARCHAR(256),
  `term` VARCHAR(256),
  `usuario_atividade_remunerada` VARCHAR(256),
  `usuario_cpf` VARCHAR(256),
  `usuario_data_nascimento` VARCHAR(256),
  `usuario_email` VARCHAR(256),
  `usuario_empresa_bairro` VARCHAR(256),
  `usuario_empresa_cargo` VARCHAR(256),
  `usuario_empresa_cidade` VARCHAR(256),
  `usuario_empresa_data` VARCHAR(256),
  `usuario_empresa_edenreco` VARCHAR(256),
  `usuario_empresa_nome` VARCHAR(256),
  `usuario_empresa_outros_rendimentos` VARCHAR(256),
  `usuario_empresa_salario` VARCHAR(256),
  `usuario_empresa_telefone` VARCHAR(256),
  `usuario_empresa_uf` VARCHAR(256),
  `usuario_estado_civil` VARCHAR(256),
  `usuario_nacionalidade` VARCHAR(256),
  `usuario_naturalidade` VARCHAR(256),
  `usuario_profissao` VARCHAR(256),
  `usuario_rg` VARCHAR(256),
  `usuario_telefone` VARCHAR(256),
  `usuario_telefone_celular` VARCHAR(256),
  `usuario_usuario_name` VARCHAR(256),
  `valor_aluguel` VARCHAR(256),
  `veiculo_dados` VARCHAR(256),
  `veiculo_financiado` VARCHAR(256),
  `veiculo_placa` VARCHAR(256),
  `veiculo_valor` VARCHAR(256),
  PRIMARY KEY (`id`)
) ENGINE  = InnoDB;

CREATE INDEX usuario_cpf ON user(usuario_cpf);


